from enum import Enum


class SessionStatus(str, Enum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    SQL_READY_PENDING_UPSTREAM = "SQL_READY_PENDING_UPSTREAM"
    UPSTREAM_CONFIRMED_SUCCESS = "UPSTREAM_CONFIRMED_SUCCESS"
    HUMAN_REQUIRED = "HUMAN_REQUIRED"
    SYSTEM_ERROR = "SYSTEM_ERROR"


class AttemptStatus(str, Enum):
    CREATED = "CREATED"
    DIAGNOSED = "DIAGNOSED"
    PLANNED = "PLANNED"
    GENERATED = "GENERATED"
    VALIDATION_BLOCKED = "VALIDATION_BLOCKED"
    REFLECTION_BLOCKED = "REFLECTION_BLOCKED"
    SQL_READY = "SQL_READY"
    UPSTREAM_FAILED = "UPSTREAM_FAILED"
    UPSTREAM_CONFIRMED_SUCCESS = "UPSTREAM_CONFIRMED_SUCCESS"
    HUMAN_REQUIRED = "HUMAN_REQUIRED"
    SYSTEM_ERROR = "SYSTEM_ERROR"
