from enum import Enum


class SessionStatus(str, Enum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    SQL_READY_PENDING_UPSTREAM = "SQL_READY_PENDING_UPSTREAM"
    UPSTREAM_CONFIRMED_SUCCESS = "UPSTREAM_CONFIRMED_SUCCESS"
    HUMAN_REQUIRED = "HUMAN_REQUIRED"
    SYSTEM_ERROR = "SYSTEM_ERROR"


class AttemptStatus(str, Enum):
    CREATED = "CREATED"
    DIAGNOSED = "DIAGNOSED"
    PLANNED = "PLANNED"
    GENERATED = "GENERATED"
    VALIDATION_BLOCKED = "VALIDATION_BLOCKED"
    REFLECTION_BLOCKED = "REFLECTION_BLOCKED"
    SQL_READY = "SQL_READY"
    UPSTREAM_FAILED = "UPSTREAM_FAILED"
    UPSTREAM_CONFIRMED_SUCCESS = "UPSTREAM_CONFIRMED_SUCCESS"
    HUMAN_REQUIRED = "HUMAN_REQUIRED"
    SYSTEM_ERROR = "SYSTEM_ERROR"


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    BLOCKED = "BLOCKED"


class DiagnosedErrorType(str, Enum):
    SQL_SYNTAX_ERROR = "SQL_SYNTAX_ERROR"
    COLUMN_NOT_FOUND = "COLUMN_NOT_FOUND"
    TABLE_NOT_FOUND = "TABLE_NOT_FOUND"
    AMBIGUOUS_COLUMN = "AMBIGUOUS_COLUMN"
    TYPE_MISMATCH = "TYPE_MISMATCH"
    INVALID_FUNCTION = "INVALID_FUNCTION"
    AGGREGATION_ERROR = "AGGREGATION_ERROR"
    PARTITION_ERROR = "PARTITION_ERROR"
    DIALECT_INCOMPATIBILITY = "DIALECT_INCOMPATIBILITY"
    PERMISSION_ERROR = "PERMISSION_ERROR"
    RESOURCE_EXHAUSTED = "RESOURCE_EXHAUSTED"
    INFRASTRUCTURE_ERROR = "INFRASTRUCTURE_ERROR"
    DATA_QUALITY_ERROR = "DATA_QUALITY_ERROR"
    UNKNOWN = "UNKNOWN"
